tables:
  companies:
    fields:
      id: true
      name:
        type: string
        length: 255
        unique: true
      url:
        type: string
        length: 2048
      logo:
        type: text
        nullable: true
      annual_revenue:
        type: decimal
        precision: 15
        scale: 2
        nullable: true
      operating_income:
        type: decimal
        precision: 15
        scale: 2
        nullable: true
      net_income:
        type: decimal
        precision: 15
        scale: 2
        nullable: true
      total_assets:
        type: decimal
        precision: 15
        scale: 2
        nullable: true
      total_equity:
        type: decimal
        precision: 15
        scale: 2
        nullable: true
      timestamps: true

  subjects:
    fields:
      id: true
      company_id:
        type: foreignId
        foreign_key: companies.id
      name:
        type: string
        length: 255
        unique: true
      url:
        type: string
        length: 2048
      logo:
        type: text
        nullable: true
      patent_number:
        type: string
        nullable: true
      patent_filed_date:
        type: date
        nullable: true
      patent_expiration_date:
        type: date
        nullable: true
      patent_issued_date:
        type: date
        nullable: true
      patent_details:
        type: text
        nullable: true
      number_of_users:
        type: integer
        nullable: true
      market_share:
        type: decimal
        precision: 5
        scale: 2
        nullable: true
      generic_name:
        type: string
        length: 255
        nullable: true
      generics:
        type: json
        nullable: true
      statute_of_limitations_tolling:
        type: text
        nullable: true
      timestamps: true

  issues:
    fields:
      id: true
      subject_id:
        type: foreignId
        foreign_key: subjects.id
      is_dashboard_approved:
        type: boolean
        default: false
      name:
        type: string
        length: 255
        unique: true
      description:
        type: text
        nullable: true
      evaluation_score:
        type: integer
        nullable: true
      severity_level:
        type: string
        length: 50
        nullable: true
      hospitalization:
        type: boolean
        nullable: true
      surgical_procedure:
        type: boolean
        nullable: true
      permanent_disability:
        type: boolean
        nullable: true
      death:
        type: boolean
        nullable: true
      ongoing_care:
        type: boolean
        nullable: true
      economic_damage_min:
        type: decimal
        precision: 10
        scale: 2
        nullable: true
      economic_damage_max:
        type: decimal
        precision: 10
        scale: 2
        nullable: true
      timestamps: true

  scientific_studies:
    fields:
      id: true
      subject_id:
        type: foreignId
        foreign_key: subjects.id
      issue_id:
        type: foreignId
        foreign_key: issues.id
      name:
        type: string
        length: 255
        unique: true
      url:
        type: string
        length: 2048
      description:
        type: text
        nullable: true
      quality_grade:
        type: string
        length: 5
        nullable: true
      injury:
        type: string
        length: 255
        nullable: true
      injury_description:
        type: text
        nullable: true
      group_size:
        type: integer
        nullable: true
      age_range:
        type: string
        nullable: true
      median_age:
        type: string
        nullable: true
      treatment_method:
        type: text
        nullable: true
      treatment_efficacy:
        type: text
        nullable: true
      complications:
        type: text
        nullable: true
      timestamps: true

  warnings:
    fields:
      id: true
      subject_id:
        type: foreignId
        foreign_key: subjects.id
      issue_id:
        type: foreignId
        foreign_key: issues.id
      name:
        type: string
        length: 255
        unique: true
      url:
        type: string
        length: 2048
        nullable: true
      description:
        type: text
        nullable: true
      issued_at:
        type: datetime
        nullable: true
      injury_risks:
        type: json
        nullable: true

  data_sources:
    auto_ref: [ "table", "record_id", "field" ]
    fields:
      id: true
      name:
        type: string
        length: 255
      url:
        type: string
        length: 2048
      table:
        type: string
        length: 255
      record_id:
        type: integer
      field:
        type: string
        length: 255
      explanation:
        type: text
        nullable: true
      timestamps: true
    indexes:
      - name: unique_data_table_record_field
        columns: [ table, record_id, field ]
        unique: true
