DrugInjury:
  attributes:
    - name: evaluation_score
      type: integer
      description: The evaluation score of the injury
    - name: severity_level
      type: integer
      description: The severity level of the injury
    - name: hospitalization
      type: boolean
      description: Whether the injury required hospitalization
    - name: surgical_procedure
      type: boolean
      description: Whether the injury required a surgical procedure
    - name: permanent_disability
      type: boolean
      description: Whether the injury resulted in permanent disability
    - name: death
      type: boolean
      description: Whether the injury resulted in death
    - name: ongoing_care
      type: boolean
      description: Whether the injury requires ongoing care
    - name: economic_damage_min
      type: decimal
      description: The minimum economic damage caused by the injury
    - name: economic_damage_max
      type: decimal
      description: The maximum economic damage caused by the injury
  relations:
    DrugProduct:
      type: DrugProduct
      cardinality: 1
      attributes:
        - name: number_of_users
          type: integer
          description: The number of users of the patented product
        - name: market_share
          type: decimal
          description: The market share of the patented product
        - name: statute_of_limitations_tolling
          type: text
          description: The statute of limitations tolling for the patent
      relations:
        Patents:
          type: Patent
          cardinality: many
          attributes:
            - name: patent_number
              type: string
              description: The patent number
            - name: patent_filed_date
              type: date
              description: The date the patent was filed
            - name: patent_expiration_date
              type: date
              description: The date the patent expires
            - name: patent_issued_date
              type: date
              description: The date the patent was issued
        DrugGenerics:
          type: DrugGeneric
          cardinality: many
          attributes:
            - name: generics
              type: json
              description: A list of generic versions of the patented product
            - name: statute_of_limitations_tolling
              type: text
              description: The statute of limitations tolling for the patent
        Company:
          type: Company
          cardinality: 1
          attributes:
            - name: net_income
              type: integer
              description: Most recent annual net income
            - name: annual_revenue
              type: integer
              description: Last year's recent annual revenue
            - name: operating_income
              type: integer
              description: Most recent annual operating income
            - name: total_assets
              type: integer
              description: Most recent total assets
            - name: total_equity
              type: integer
              description: Most recent total equity
    ScientificStudies:
      type: ScientificStudy
      cardinality: many
      attributes:
        - name: group_size
          type: integer
          description: The size of the study group
        - name: age_range
          type: string
          description: The age range of the study group
        - name: median_age
          type: string
          description: The median age of the study group
        - name: treatment_method
          type: text
          description: The treatment method used in the study
        - name: treatment_efficacy
          type: text
          description: The efficacy of the treatment used in the study
        - name: complications
          type: text
          description: The complications observed in the study
    Warnings:
      type: Warning
      cardinality: many
      attributes:
        - name: issued_at
          type: date
          description: The date the warning was issued
        - name: injury_risks
          type: json
          description: A list of injury risks associated with the warning
